export const categories = [
  {
    category: "People",
    images: [
      {
        slug: "my-father",
        title: "My Father",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "60 x 40 cm",
        image: "/images/artwork1.JPG",
        carousel: true
      },
      {
        slug: "ulrico",
        title: "Ulrico",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "30 x 30 cm",
        image: "/images/artwork2.jpg",
        carousel: true
      },
      {
        slug: "Anni",
        title: "Anni",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "20 x 20 cm",
        image: "/images/artwork3.jpg",
        carousel: true
      },
      {
        slug: "the-woods",
        title: "The Woods",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "60 x 80 cm",
        image: "/images/artwork4.jpg",
      },
      {
        slug: "elena",
        title: "Elena",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "40 x 50 cm",
        image: "/images/artwork5.jpg",
        carousel: true,
      },
      {
        slug: "guido",
        title: "Guido",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "40 x 50 cm",
        image: "/images/artwork6.jpg",
      },
      {
        slug: "motherhood",
        title: "Motherhood",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "30 x 30 cm",
        image: "/images/artwork7.jpg",
        carousel: true
      },
      {
        slug: "woman-in-black",
        title: "Woman in Black",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "30 x 30 cm",
        image: "/images/artwork8.jpg",
      },
      {
        slug: "family",
        title: "Family",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "60 x 90 cm",
        image: "/images/artwork9.jpg",
      },
      {
        slug: "isabella",
        title: "Isabella",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "30 x 30 cm",
        image: "/images/artwork10.jpg",
      },
      {
        slug: "mari-in-the-garden",
        title: "Marí in the Garden",
        medium: "Oil on Canvas",
        year: "2021",
        dimensions: "60 x 80 cm",
        image: "/images/artwork11.jpg",
      },
      {
        slug: "margherita-in-the-wind",
        title: "Margherita in the Wind",
        medium: "Graphite",
        year: "2020",
        dimensions: "21 x 29.7 cm",
        image: "/images/artwork12.jpg",
      },
      {
        slug: "andrea",
        title: "Andrea",
        medium: "Oil on Canvas",
        year: "2020",
        dimensions: "120 x 100 cm",
        image: "/images/artwork13.jpeg",
      },
    ],
  },
  {
    category: "Still Life",
    images: [
      {
        slug: "parrot",
        title: "Parrot",
        medium: "Oil on Canvas",
        year: "2022",
        dimensions: "60 x 80 cm",
        image: "/images/still1.jpg",
      },
      {
        slug: "london-view",
        title: "London View",
        medium: "Oil on Canvas",
        year: "2023",
        dimensions: "20 x 50 cm",
        image: "/images/still2.jpg",
      },
      {
        slug: "chappa-la-gallina",
        title: "Chappa la Gallina",
        medium: "Oil on Canvas",
        year: "2022",
        dimensions: "40 x 50 cm",
        image: "/images/still3.jpg",
      },
      {
        slug: "the-wild-garden",
        title: "The Wild Garden",
        medium: "Oil on Canvas",
        year: "2023",
        dimensions: "60 x 80 cm",
        image: "/images/still4.jpg",
      },
      {
        slug: "philodendron",
        title: "Philodendron",
        medium: "Oil on Canvas",
        year: "2023",
        dimensions: "60 x 80 cm",
        image: "/images/still5.jpg",
      },
      {
        slug: "tucano",
        title: "Tucano",
        medium: "Oil on Canvas",
        year: "2023",
        dimensions: "60 x 80 cm",
        image: "/images/still6.jpg",
      },

    ],
  },
  {
    category: "Cut-Outs",
    images: [
      {
        slug: "ulrich",
        title: "Ulrico",
        medium: "Paper Cut-out",
        year: "2019",
        dimensions: "60 x 80 cm",
        image: "/images/cutout1.jpg",
      },
      {
        slug: "sitting-woman",
        title: "Sitting Woman",
        medium: "Paper Cut-out",
        year: "2020",
        dimensions: "30 x 30 cm",
        image: "/images/cutout2.jpg",
      },
      {
        slug: "pasture-in-high-engadine",
        title: "Pasture in High Engadine",
        medium: "Paper Cut-out",
        year: "2020",
        dimensions: "30 x 40 cm",
        image: "/images/cutout3.jpeg",
      },
      {
        slug: "amalia",
        title: "Amalia",
        medium: "Paper Cut-out",
        year: "2019",
        dimensions: "50 x 70 cm",
        image: "/images/cutout4.jpg",
      },
      {
        slug: "cut-out-title-5",
        title: "Cut-out Title 5",
        medium: "Paper Cut-out",
        year: "2024",
        dimensions: "30 x 40 cm",
        image: "/images/cutout5.jpg",
      },
      {
        slug: "cut-out-title-6",
        title: "Cut-out Title 6",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout6.jpg",
      },
      {
        slug: "cut-out-title-7",
        title: "Cut-out Title 7",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout7.jpg",
      },
      {
        slug: "cut-out-title-8",
        title: "Cut-out Title 8",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout8.jpg",
      },
      {
        slug: "cut-out-title-9",
        title: "Cut-out Title 9",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout9.jpg",
      },
      {
        slug: "cut-out-title-10",
        title: "Cut-out Title 10",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout10.jpg",
      },
      {
        slug: "cut-out-title-11",
        title: "Cut-out Title 11",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/cutout11.jpg",
      },
    ],
  },
  {
    category: "Comics",
    images: [
      {
        slug: "comic1",
        title: "Comic 1",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/comic1.jpg",
      },
      {
        slug: "comic2",
        title: "Comic 2",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/comic2.jpg",
      },
      {
        slug: "comic3",
        title: "Comic 3",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/comic3.jpg",
      },
      {
        slug: "comic4",
        title: "Comic 4",
        medium: "Paper Cut-out",
        year: "2023",
        dimensions: "25 x 35 cm",
        image: "/images/comic4.jpg",
      },
    ],
  },
  {
    category: "Paper Folding",
    images: [],
  },
]

export const exhibitions = [
  {
    name: 'Linea',
    date: 'March 2020',
    location: 'New York, NY, USA',
    link: 'https://asllinea.org/pandemic-art-exhibition/',
    image: "/images/exh1.jpeg",
  },
  {
    name: 'Portraing Life in a Modern House',
    date: 'May 2022',
    location: 'Chiasso, Switzerland',
    link: 'https://www.demosmobilia.ch/portraiting-life-in-a-modern-house/',
    image: "/images/exh2.jpg",
  },
]